export default {
  matches: [
    {
      id: 1,
      home_team: "Barcelona",
      away_team: "Real Madrid",
      start: "2024-10-03 11:00",
      time: "20:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 2,
      home_team: "Manchester United",
      away_team: "Juventus",
      start: "2024-10-05 11:00",
      time: "19:45",
      type: "soccer",
      location: "Old Trafford",
    },
    {
      id: 3,
      home_team: "Bayern Munich",
      away_team: "Barcelona",
      start: "2024-10-02 11:00",
      time: "20:00",
      type: "soccer",
      location: "Allianz Arena",
    },
    {
      id: 4,
      home_team: "Real Madrid",
      away_team: "Bayern Munich",
      start: "2024-10-04 11:00",
      time: "19:45",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
    {
      id: 5,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-10-05 19:30",
      time: "19:30",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 6,
      home_team: "Team USA",
      away_team: "Brazil Volleyball",
      start: "2024-10-03 14:00",
      time: "14:00",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 7,
      home_team: "Toronto Maple Leafs",
      away_team: "New York Rangers",
      start: "2024-10-06 18:00",
      time: "18:00",
      type: "hockey",
      location: "Scotiabank Arena",
    },
    {
      id: 8,
      home_team: "Chicago Bulls",
      away_team: "Los Angeles Lakers",
      start: "2024-10-02 20:00",
      time: "20:00",
      type: "basketball",
      location: "United Center",
    },
    {
      id: 9,
      home_team: "Brazil Volleyball",
      away_team: "Team USA",
      start: "2024-10-04 15:30",
      time: "15:30",
      type: "volleyball",
      location: "Maracanãzinho",
    },
    {
      id: 10,
      home_team: "New York Rangers",
      away_team: "Toronto Maple Leafs",
      start: "2024-10-06 17:00",
      time: "17:00",
      type: "hockey",
      location: "Madison Square Garden",
    },
    {
      id: 11,
      home_team: "Los Angeles Lakers",
      away_team: "Golden State Warriors",
      start: "2024-10-05 19:00",
      time: "19:00",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 12,
      home_team: "Barcelona",
      away_team: "Juventus",
      start: "2024-10-20 18:00",
      time: "18:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 13,
      home_team: "Real Madrid",
      away_team: "Manchester United",
      start: "2024-10-21 20:00",
      time: "20:00",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
    {
      id: 14,
      home_team: "Bayern Munich",
      away_team: "Barcelona",
      start: "2024-10-22 17:00",
      time: "17:00",
      type: "soccer",
      location: "Allianz Arena",
    },
    {
      id: 15,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-10-23 19:30",
      time: "19:30",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 16,
      home_team: "Team USA",
      away_team: "Brazil Volleyball",
      start: "2024-10-24 15:30",
      time: "15:30",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 17,
      home_team: "Toronto Maple Leafs",
      away_team: "New York Rangers",
      start: "2024-10-25 18:30",
      time: "18:30",
      type: "hockey",
      location: "Scotiabank Arena",
    },
    {
      id: 18,
      home_team: "Barcelona",
      away_team: "Real Madrid",
      start: "2024-10-26 20:00",
      time: "20:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 19,
      home_team: "Manchester United",
      away_team: "Juventus",
      start: "2024-10-27 16:00",
      time: "16:00",
      type: "soccer",
      location: "Old Trafford",
    },
    {
      id: 20,
      home_team: "New York Rangers",
      away_team: "Toronto Maple Leafs",
      start: "2024-10-28 19:00",
      time: "19:00",
      type: "hockey",
      location: "Madison Square Garden",
    },
    {
      id: 21,
      home_team: "Chicago Bulls",
      away_team: "Los Angeles Lakers",
      start: "2024-10-29 20:30",
      time: "20:30",
      type: "basketball",
      location: "United Center",
    },
    {
      id: 22,
      home_team: "Team USA",
      away_team: "Brazil Volleyball",
      start: "2024-10-30 13:00",
      time: "13:00",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 23,
      home_team: "Barcelona",
      away_team: "Real Madrid",
      start: "2024-11-01 20:00",
      time: "20:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 24,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-11-02 19:00",
      time: "19:00",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 25,
      home_team: "Juventus",
      away_team: "Manchester United",
      start: "2024-11-03 18:00",
      time: "18:00",
      type: "soccer",
      location: "Allianz Stadium",
    },
    {
      id: 26,
      home_team: "Real Madrid",
      away_team: "Bayern Munich",
      start: "2024-11-04 20:45",
      time: "20:45",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
    {
      id: 27,
      home_team: "Chicago Bulls",
      away_team: "Golden State Warriors",
      start: "2024-11-05 19:00",
      time: "19:00",
      type: "basketball",
      location: "United Center",
    },
    {
      id: 28,
      home_team: "Team USA",
      away_team: "Canada Volleyball",
      start: "2024-11-06 15:30",
      time: "15:30",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 29,
      home_team: "Toronto Maple Leafs",
      away_team: "Boston Bruins",
      start: "2024-11-07 18:00",
      time: "18:00",
      type: "hockey",
      location: "Scotiabank Arena",
    },
    {
      id: 30,
      home_team: "New York Rangers",
      away_team: "Toronto Maple Leafs",
      start: "2024-11-08 19:30",
      time: "19:30",
      type: "hockey",
      location: "Madison Square Garden",
    },
    {
      id: 31,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-11-09 21:00",
      time: "21:00",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 31,
      home_team: "Barcelona",
      away_team: "Juventus",
      start: "2024-10-20 18:00",
      time: "18:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 32,
      home_team: "Real Madrid",
      away_team: "Manchester United",
      start: "2024-10-21 20:00",
      time: "20:00",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
    {
      id: 33,
      home_team: "Bayern Munich",
      away_team: "Barcelona",
      start: "2024-10-22 17:00",
      time: "17:00",
      type: "soccer",
      location: "Allianz Arena",
    },
    {
      id: 34,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-10-23 19:30",
      time: "19:30",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 35,
      home_team: "Team USA",
      away_team: "Brazil Volleyball",
      start: "2024-10-24 15:30",
      time: "15:30",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 36,
      home_team: "Toronto Maple Leafs",
      away_team: "New York Rangers",
      start: "2024-10-25 18:30",
      time: "18:30",
      type: "hockey",
      location: "Scotiabank Arena",
    },
    {
      id: 37,
      home_team: "Barcelona",
      away_team: "Real Madrid",
      start: "2024-10-26 20:00",
      time: "20:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 38,
      home_team: "Manchester United",
      away_team: "Juventus",
      start: "2024-10-27 16:00",
      time: "16:00",
      type: "soccer",
      location: "Old Trafford",
    },
    {
      id: 39,
      home_team: "New York Rangers",
      away_team: "Toronto Maple Leafs",
      start: "2024-10-28 19:00",
      time: "19:00",
      type: "hockey",
      location: "Madison Square Garden",
    },
    {
      id: 40,
      home_team: "Chicago Bulls",
      away_team: "Los Angeles Lakers",
      start: "2024-10-29 20:30",
      time: "20:30",
      type: "basketball",
      location: "United Center",
    },
    {
      id: 41,
      home_team: "Team USA",
      away_team: "Brazil Volleyball",
      start: "2024-10-30 13:00",
      time: "13:00",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 42,
      home_team: "Barcelona",
      away_team: "Real Madrid",
      start: "2024-11-01 20:00",
      time: "20:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 43,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-11-02 19:00",
      time: "19:00",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 44,
      home_team: "Juventus",
      away_team: "Manchester United",
      start: "2024-11-03 18:00",
      time: "18:00",
      type: "soccer",
      location: "Allianz Stadium",
    },
    {
      id: 45,
      home_team: "Real Madrid",
      away_team: "Bayern Munich",
      start: "2024-11-04 20:45",
      time: "20:45",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
    {
      id: 46,
      home_team: "Chicago Bulls",
      away_team: "Golden State Warriors",
      start: "2024-11-05 19:00",
      time: "19:00",
      type: "basketball",
      location: "United Center",
    },
    {
      id: 47,
      home_team: "Team USA",
      away_team: "Canada Volleyball",
      start: "2024-11-06 15:30",
      time: "15:30",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 48,
      home_team: "Toronto Maple Leafs",
      away_team: "Boston Bruins",
      start: "2024-11-07 18:00",
      time: "18:00",
      type: "hockey",
      location: "Scotiabank Arena",
    },
    {
      id: 49,
      home_team: "New York Rangers",
      away_team: "Toronto Maple Leafs",
      start: "2024-11-08 19:30",
      time: "19:30",
      type: "hockey",
      location: "Madison Square Garden",
    },
    {
      id: 50,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-11-09 21:00",
      time: "21:00",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 51,
      home_team: "Barcelona",
      away_team: "Bayern Munich",
      start: "2024-10-20 16:00",
      time: "16:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 52,
      home_team: "Juventus",
      away_team: "Real Madrid",
      start: "2024-10-21 18:00",
      time: "18:00",
      type: "soccer",
      location: "Allianz Stadium",
    },
    {
      id: 53,
      home_team: "New York Rangers",
      away_team: "Toronto Maple Leafs",
      start: "2024-10-23 19:00",
      time: "19:00",
      type: "hockey",
      location: "Madison Square Garden",
    },
    {
      id: 54,
      home_team: "Toronto Maple Leafs",
      away_team: "New York Rangers",
      start: "2024-10-24 18:30",
      time: "18:30",
      type: "hockey",
      location: "Scotiabank Arena",
    },
    {
      id: 55,
      home_team: "Team USA",
      away_team: "Brazil Volleyball",
      start: "2024-10-25 15:00",
      time: "15:00",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 56,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-10-26 20:00",
      time: "20:00",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 57,
      home_team: "Bayern Munich",
      away_team: "Juventus",
      start: "2024-10-27 16:30",
      time: "16:30",
      type: "soccer",
      location: "Allianz Arena",
    },
    {
      id: 58,
      home_team: "Real Madrid",
      away_team: "Manchester United",
      start: "2024-10-28 20:00",
      time: "20:00",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
    {
      id: 59,
      home_team: "Juventus",
      away_team: "Barcelona",
      start: "2024-10-29 18:00",
      time: "18:00",
      type: "soccer",
      location: "Allianz Stadium",
    },
    {
      id: 60,
      home_team: "Manchester United",
      away_team: "Real Madrid",
      start: "2024-11-01 16:00",
      time: "16:00",
      type: "soccer",
      location: "Old Trafford",
    },
  ],
};
