export default {
  matches: [
    {
      id: 1,
      home_team: "Barcelona",
      away_team: "Real Madrid",
      start: "2024-10-3 11:00",
      time: "20:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 2,
      home_team: "Manchester United",
      away_team: "Juventus",
      start: "2024-10-5 11:00",
      time: "19:45",
      type: "soccer",
      location: "Old Trafford",
    },
    {
      id: 3,
      home_team: "Bayern Munich",
      away_team: "Barcelona",
      start: "2024-10-2 11:00",
      time: "20:00",
      type: "soccer",
      location: "Allianz Arena",
    },
    {
      id: 4,
      home_team: "Real Madrid",
      away_team: "Bayern Munich",
      start: "2024-10-4 11:00",
      time: "19:45",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
    {
      id: 5,
      home_team: "Los Angeles Lakers",
      away_team: "Chicago Bulls",
      start: "2024-10-05 19:30",
      time: "19:30",
      type: "basketball",
      location: "Staples Center",
    },
    {
      id: 6,
      home_team: "Team USA",
      away_team: "Brazil Volleyball",
      start: "2024-10-3 14:00",
      time: "14:00",
      type: "volleyball",
      location: "Tokyo Dome",
    },
    {
      id: 7,
      home_team: "Toronto Maple Leafs",
      away_team: "New York Rangers",
      start: "2024-10-6 18:00",
      time: "18:00",
      type: "hockey",
      location: "Scotiabank Arena",
    },
    {
      id: 8,
      home_team: "Chicago Bulls",
      away_team: "Los Angeles Lakers",
      start: "2024-10-02 20:00",
      time: "20:00",
      type: "basketball",
      location: "United Center",
    },
    {
      id: 9,
      home_team: "Brazil Volleyball",
      away_team: "Team USA",
      start: "2024-10-04 15:30",
      time: "15:30",
      type: "volleyball",
      location: "Maracanãzinho",
    },
    {
      id: 10,
      home_team: "New York Rangers",
      away_team: "Toronto Maple Leafs",
      start: "2024-10-6 17:00",
      time: "17:00",
      type: "hockey",
      location: "Madison Square Garden",
    },
    {
      id: 11,
      home_team: "Los Angeles Lakers",
      away_team: "Golden State Warriors",
      start: "2024-10-05 19:00",
      time: "19:00",
      type: "basketball",
      location: "Staples Center",
    },
  ],
};
