export default {
  matches: [
    {
      id: 1,
      home_team: "Barcelona",
      away_team: "Real Madrid",
      start: "2024-10-3 11:00",
      time: "20:00",
      type: "soccer",
      location: "Camp Nou",
    },
    {
      id: 2,
      home_team: "Manchester United",
      away_team: "Juventus",
      start: "2024-10-5 11:00",
      time: "19:45",
      type: "soccer",
      location: "Old Trafford",
    },
    {
      id: 3,
      home_team: "Bayern Munich",
      away_team: "Barcelona",
      start: "2024-10-2 11:00",
      time: "20:00",
      type: "soccer",
      location: "Allianz Arena",
    },
    {
      id: 4,
      home_team: "Real Madrid",
      away_team: "Bayern Munich",
      start: "2024-10-4 11:00",
      time: "19:45",
      type: "soccer",
      location: "Santiago Bernabeu",
    },
  ],
};
